income/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls'), name='predict')
]

predict/urls.py
from django.urls import path
from . import views

app_name = 'predict'

urlpatterns = [
    path('', views.predict, name='predict'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),

]

predict/models.py
from django.db import models

class PredResults(models.Model):

	age = models.FloatField()
	workclass = models.CharField(max_length=100)
	education_years = models.FloatField()
	marital_status = models.CharField(max_length=100)
	relationship = models.CharField(max_length=100)
	race = models.CharField(max_length=100)
	sex = models.CharField(max_length=100)
	hours_per_week = models.FloatField()
	result = models.CharField(max_length=30)

	def __str__(self):
		return self.result




predict/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pickle
from .models import PredResults



def predict(request):
	return render(request, 'predict.html')

def predict_chances(request):
	#file = open("lr_model.pickle",encoding="utf8")
	with open('lr_model.pickle', 'rb') as handle:
		model = pickle.load(handle)

	if request.POST.get('action') == 'post':
		age = float(request.POST.get('age'))
		workclass = str(request.POST.get('workclass'))
		education_years = float(request.POST.get('education_years'))
		marital_status = str(request.POST.get('marital_status'))
		relationship = str(request.POST.get('relationship'))
		race = str(request.POST.get('race'))
		sex = str(request.POST.get('sex'))
		hours_per_week = float(request.POST.get('hours_per_week'))

	pred_lst = []
	pred_lst.extend([age,education_years,hours_per_week])

	if workclass == 'Federal-gov':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'Local-gov':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'Private':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'Self-emp-inc':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'Self-emp-not-inc':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'State-gov':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if workclass == 'Without-pay':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Divorced':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Married-AF-spouse':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Married-civ-spouse':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Married-spouse-absent':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Never-married':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Separated':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if marital_status == 'Widowed':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Husband':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Not-in-family':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Other-relative':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Own-child':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Unmarried':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if relationship == 'Wife':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if race == 'Amer-Indian-Eskimo':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if race == 'Asian-Pac-Islander':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if race == 'Black':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if race == 'Other':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if race == 'White':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if sex == 'Female':
		pred_lst.append(1)
	else:
		pred_lst.append(0)

	if sex == 'Male':
		pred_lst.append(1)
	else:
		pred_lst.append(0)


	result = model.predict([pred_lst])

	classification = result[0]

	if classification == 0:
		result = 'Income < 50k'
	elif classification == 1:
		result = 'Income > 50k'


	PredResults.objects.create(age=age, workclass=workclass, education_years=education_years,
		marital_status =marital_status, relationship=relationship, race=race, sex=sex, hours_per_week=hours_per_week, result=result)

	return JsonResponse({'result':result,'age':age,'workclass':workclass, 'education_years':education_years,
		'marital_status':marital_status, 'relationship':relationship, 'race':race,'sex':sex,'hours_per_week':hours_per_week})



def view_results(request):
	data = {"dataset": PredResults.objects.all()}
	return render(request, "results.html", data)

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Income prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Age: <span id="a"></span></div>
                <div>Workclass: <span id="wc"></span></div>
                <div>Education Years: <span id="ey"></span></div>
                <div>Marital-Status: <span id="ms"></span></div>
                <div>Relationship: <span id="re"></span></div>
                <div>Race: <span id="ra"></span></div>
                <div>Sex: <span id="s"></span></div>
                <div>Hours Per Week: <span id="hpw"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Income Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="age">Age</label>
                    <input type="number" step="1" class="form-control" id="age" placeholder="" required>
                </div>

                <div class="form-group">
                    <label for="education_years">Education Years</label>
                    <input type="number" step="0.5" class="form-control" id="education_years" placeholder="" required>
                </div>

                <div class="form-group">
                    <label for="hours_per_week">Hours Per Week</label>
                    <input type="number" step="0.1" class="form-control" id="hours_per_week" placeholder="" required>
                </div>

                <div class="form-group">
                    <label for="workclass">Workclass</label>
                    <select class="form-control" id="workclass" required>
                        <option value="Private" >Private</option>
                        <option value="Self-emp-not-inc">Self-emp-not-inc</option>
                        <option value="Local-gov">Local-gov</option>
                        <option value="State-gov">State-gov</option>
                        <option value="Federal-gov">Federal-gov</option>
                        <option value="Without-pay">Without-Pay</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="marital_status">Marital Status</label>
                    <select class="form-control" id="marital_status" required>
                        <option value="Married-civ-spouse">Married-civ-spouse</option>
                        <option value="Never-married">Never-married</option>
                        <option value="Divorced">Divorced</option>
                        <option value="Separated">Separated</option>
                        <option value="Widowed">Widowed</option>
                        <option value="Married-spouse-absent">Married-spouse-absent</option>
                        <option value="Married-AF-spouse">Married-AF-spouse</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="relationship">Relationship</label>
                    <select class="form-control" id="relationship" required> 
                        <option value="Husband" >Husband</option>
                        <option value="Not-in-family">Not-in-family</option>
                        <option value="Own-child">Own-child</option>
                        <option value="Unmarried">Unmarried</option>
                        <option value="Wife">Wife</option>
                        <option value="Other-relative">Other-relative</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="race">Race</label>
                    <select class="form-control" id="race" required>
                        <option value="White">White</option>
                        <option value="Black" >Black</option>
                        <option value="Asian-Pac-Islander">Asian-Pac-Islander</option>
                        <option value="Amer-Indian-Eskimo">Amer-Indian-Eskimo</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="sex">Sex</label>
                    <select class="form-control" id="sex" required>
                        <option value="Male" >Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
               
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                age:$('#age').val(),
                workclass:$('#workclass').val(),
                education_years:$('#education_years').val(),
                marital_status:$('#marital_status').val(),
                relationship:$('#relationship').val(),
                race:$('#race').val(),
                sex:$('#sex').val(),
                hours_per_week:$('#hours_per_week').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("a").innerHTML = json['age']
                document.getElementById("wc").innerHTML = json['workclass']
                document.getElementById("ey").innerHTML = json['education_years']
                document.getElementById("ms").innerHTML = json['marital_status']
                document.getElementById("re").innerHTML = json['relationship']
                document.getElementById("ra").innerHTML = json['race']
                document.getElementById("s").innerHTML = json['sex']
                document.getElementById("hpw").innerHTML = json['hours_per_week']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">age</th>
                <th scope="col">workclass</th>
                <th scope="col">education_years</th>
                <th scope="col">marital_status</th>
                <th scope="col">relationship</th>
                <th scope="col">race</th>
                <th scope="col">sex</th>
                <th scope="col">hours_per_week</th>
                <th scope="col">result</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.age }}</td>
                    <td>{{ data.workclass }}</td>
                    <td>{{ data.education_years }}</td>
                    <td>{{ data.marital_status }}</td>
                    <td>{{ data.relationship }}</td>
                    <td>{{ data.race }}</td>
                    <td>{{ data.sex }}</td>
                    <td>{{ data.hours_per_week }}</td>
                    <td>{{ data.result }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}